# This workflow mirrors the code to the wknd.site repository
name: Deploy to WKND-SPA.site Production
env:
  # Target repository
  TARGET_REPO: ${{ secrets.WKND_SPA_REPOSITORY }}
  TARGET_BRANCH_DEV: ${{ secrets.WKND_SPA_BRANCH_DEV }}
  TARGET_BRANCH_PROD: ${{ secrets.WKND_SPA_BRANCH_PROD }}
  USER_EMAIL: ${{ secrets.WKND_SPA_USER_EMAIL }}
  USER_NAME: ${{ secrets.WKND_SPA_USER_NAME }}
  USER_PWD: ${{ secrets.WKND_SPA_PASSWORD }}

# Only run on a push to feature/React-18-and-Pipeline-Frontend branch
on:
  push:
    branches: [ feature/React-18-and-Pipeline-Frontend ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-20.04, macos-latest, windows-latest ]
        java: [11]
        profile: [ ''] 

    steps:
      - name: Configure git with longpath enabled (for windows)
        run: git config --global core.longpaths true
      # Checkout Gibhut project
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'

      - name: Add WKND remote
        run:
          git remote add wknd-spa https://${WKND_SPA_USER_EMAIL}:${WKND_SPA_PASSWORD}@${TARGET_REPO}

      - name: Set Git config
        run: |
          git config --global user.email ${WKND_SPA_USER_EMAIL}
          git config --global user.name ${WKND_SPA_USER_NAME}

      - name: Push changes to WKND Development
        run:
          git push -u wknd-spa feature/React-18-and-Pipeline-Frontend:${TARGET_BRANCH_DEV}

      - name: Push changes to WKND Production
        run:
          git push -u wknd-spa feature/React-18-and-Pipeline-Frontend:${TARGET_BRANCH_PROD}